---

name: Builderrrr

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod 776 -R openwrt-bpi-r4-mesh
          cd openwrt-bpi-r4-mesh
          ./bpi-r4-openwrt-builder.sh
          
