---

name: Builderrrr

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Increase disk space
        # You may pin to the exact commit or the version.
        # uses: fcbg-platforms/increase-disk-space@e533c293181d7dd3ab662df371ee42174235fb85
        uses: fcbg-platforms/increase-disk-space@v0.1.0
        with:
          # If True, remove Android runtime.
          android: True
          # If True, remove .NET runtime.
          dotnet: True
          # If True, remove Haskell runtime.
          haskell: True
          # If True, remove large packages.
          large-packages: True
          # If True, remove old .NET runtime.
          old-dotnet: True

      - name: Build
        run: |
          sudo rm -rf /opt/hostedtoolcache
          cd ..
          chmod 776 -R openwrt-bpi-r4-mesh
          cd openwrt-bpi-r4-mesh
          ./bpi-r4-openwrt-builder.sh
          
